<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="nguyens-Mac.local" ignored="0" name="Default test" tests="35" failures="8" timestamp="12 Apr 2018 11:13:28 GMT" time="22.949" errors="0">
  <testcase name="@AfterMethod after_test_case_execution" time="0.001" classname="ScrumBoard.Android.FunctionalTests.QTiumDemo">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at com.logigear.qtium.driver.QTiumDriverManager.getDriver(QTiumDriverManager.java:17)
at com.logigear.qtium.driver.QTiumDriverManager.closeWebDriver(QTiumDriverManager.java:79)
at com.logigear.selenium.QTiumAutomation.close(QTiumAutomation.java:484)
at ScrumBoard.Android.FunctionalTests.QTiumDemo.after_test_case_execution(QTiumDemo.java:31)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:455)
at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- @AfterMethod after_test_case_execution -->
  <testcase name="@AfterMethod after_test_case_execution" time="0.0" classname="ScrumBoard.Android.FunctionalTests.QTiumDemo">
    <skipped/>
  </testcase> <!-- @AfterMethod after_test_case_execution -->
  <testcase name="@AfterMethod after_test_case_execution" time="0.0" classname="ScrumBoard.Android.FunctionalTests.QTiumDemo">
    <skipped/>
  </testcase> <!-- @AfterMethod after_test_case_execution -->
  <testcase name="@AfterMethod after_test_case_execution" time="0.0" classname="ScrumBoard.Android.FunctionalTests.QTiumDemo">
    <skipped/>
  </testcase> <!-- @AfterMethod after_test_case_execution -->
  <testcase name="@AfterMethod after_test_case_execution" time="0.0" classname="ScrumBoard.Android.FunctionalTests.QTiumDemo">
    <skipped/>
  </testcase> <!-- @AfterMethod after_test_case_execution -->
  <testcase name="@AfterMethod after_test_case_execution" time="0.0" classname="ScrumBoard.Android.FunctionalTests.QTiumDemo">
    <skipped/>
  </testcase> <!-- @AfterMethod after_test_case_execution -->
  <testcase name="@AfterMethod after_test_case_execution" time="0.0" classname="ScrumBoard.Android.FunctionalTests.QTiumDemo">
    <skipped/>
  </testcase> <!-- @AfterMethod after_test_case_execution -->
  <testcase name="@AfterMethod after_test_case_execution" time="0.0" classname="ScrumBoard.Android.FunctionalTests.QTiumDemo">
    <skipped/>
  </testcase> <!-- @AfterMethod after_test_case_execution -->
  <testcase name="@AfterClass tear_down" time="0.0" classname="ScrumBoard.Android.FunctionalTests.QTiumDemo">
    <skipped/>
  </testcase> <!-- @AfterClass tear_down -->
  <testcase name="@AfterMethod after_test_case_execution" time="0.0" classname="ScrumBoard.FunctionalTests.QTiumDemo">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at com.logigear.qtium.driver.QTiumDriverManager.getDriver(QTiumDriverManager.java:17)
at com.logigear.qtium.driver.QTiumDriverManager.closeWebDriver(QTiumDriverManager.java:79)
at com.logigear.selenium.QTiumAutomation.close(QTiumAutomation.java:484)
at ScrumBoard.FunctionalTests.QTiumDemo.after_test_case_execution(QTiumDemo.java:29)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:455)
at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- @AfterMethod after_test_case_execution -->
  <testcase name="@AfterMethod after_test_case_execution" time="0.0" classname="ScrumBoard.FunctionalTests.QTiumDemo">
    <skipped/>
  </testcase> <!-- @AfterMethod after_test_case_execution -->
  <testcase name="@AfterMethod after_test_case_execution" time="0.0" classname="ScrumBoard.FunctionalTests.QTiumDemo">
    <skipped/>
  </testcase> <!-- @AfterMethod after_test_case_execution -->
  <testcase name="@AfterMethod after_test_case_execution" time="0.0" classname="ScrumBoard.FunctionalTests.QTiumDemo">
    <skipped/>
  </testcase> <!-- @AfterMethod after_test_case_execution -->
  <testcase name="@AfterMethod after_test_case_execution" time="0.0" classname="ScrumBoard.FunctionalTests.QTiumDemo">
    <skipped/>
  </testcase> <!-- @AfterMethod after_test_case_execution -->
  <testcase name="@AfterMethod after_test_case_execution" time="0.0" classname="ScrumBoard.FunctionalTests.QTiumDemo">
    <skipped/>
  </testcase> <!-- @AfterMethod after_test_case_execution -->
  <testcase name="@AfterMethod after_test_case_execution" time="0.0" classname="ScrumBoard.FunctionalTests.QTiumDemo">
    <skipped/>
  </testcase> <!-- @AfterMethod after_test_case_execution -->
  <testcase name="@AfterMethod after_test_case_execution" time="0.0" classname="ScrumBoard.FunctionalTests.QTiumDemo">
    <skipped/>
  </testcase> <!-- @AfterMethod after_test_case_execution -->
  <testcase name="@AfterMethod after_test_case_execution" time="0.0" classname="ScrumBoard.FunctionalTests.QTiumDemo">
    <skipped/>
  </testcase> <!-- @AfterMethod after_test_case_execution -->
  <testcase name="@AfterClass tear_down" time="0.0" classname="ScrumBoard.FunctionalTests.QTiumDemo">
    <skipped/>
  </testcase> <!-- @AfterClass tear_down -->
  <testcase name="@AfterMethod tear_down" time="16.104" classname="FptShop.FunctionalTests.QTiumDemo">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at com.logigear.qtium.driver.QTiumDriverManager.getDriver(QTiumDriverManager.java:17)
at com.logigear.qtium.driver.QTiumDriverManager.closeWebDriver(QTiumDriverManager.java:79)
at com.logigear.selenium.QTiumAutomation.close(QTiumAutomation.java:484)
at FptShop.FunctionalTests.QTiumDemo.tear_down(QTiumDemo.java:56)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:455)
at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- @AfterMethod tear_down -->
  <testcase name="@AfterMethod tear_down" time="0.0" classname="FptShop.FunctionalTests.QTiumDemo">
    <skipped/>
  </testcase> <!-- @AfterMethod tear_down -->
  <testcase name="@AfterMethod tear_down" time="0.0" classname="FptShop.FunctionalTests.QTiumDemo">
    <skipped/>
  </testcase> <!-- @AfterMethod tear_down -->
  <testcase name="@AfterMethod tear_down" time="0.0" classname="FptShop.FunctionalTests.QTiumDemo">
    <skipped/>
  </testcase> <!-- @AfterMethod tear_down -->
  <testcase name="@AfterClass tear_down" time="0.005" classname="NativeMac.FunctionalTests.NativeAppDemo">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at com.logigear.qtium.driver.QTiumDriverManager.getDriver(QTiumDriverManager.java:17)
at com.logigear.qtium.driver.QTiumDriverManager.closeWebDriver(QTiumDriverManager.java:79)
at com.logigear.selenium.QTiumAutomation.close(QTiumAutomation.java:484)
at NativeMac.FunctionalTests.NativeAppDemo.tear_down(NativeAppDemo.java:60)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:455)
at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)
at org.testng.internal.TestMethodWorker.invokeAfterClassMethods(TestMethodWorker.java:214)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- @AfterClass tear_down -->
  <testcase name="@AfterMethod after_test_case_execution" time="0.001" classname="ScrumBoard.iOS.FunctionalTests.QTiumDemo">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at com.logigear.qtium.driver.QTiumDriverManager.getDriver(QTiumDriverManager.java:17)
at com.logigear.qtium.driver.QTiumDriverManager.closeWebDriver(QTiumDriverManager.java:79)
at com.logigear.selenium.QTiumAutomation.close(QTiumAutomation.java:484)
at ScrumBoard.iOS.FunctionalTests.QTiumDemo.after_test_case_execution(QTiumDemo.java:29)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:455)
at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- @AfterMethod after_test_case_execution -->
  <testcase name="@AfterMethod after_test_case_execution" time="0.0" classname="ScrumBoard.iOS.FunctionalTests.QTiumDemo">
    <skipped/>
  </testcase> <!-- @AfterMethod after_test_case_execution -->
  <testcase name="@AfterMethod after_test_case_execution" time="0.0" classname="ScrumBoard.iOS.FunctionalTests.QTiumDemo">
    <skipped/>
  </testcase> <!-- @AfterMethod after_test_case_execution -->
  <testcase name="@AfterMethod after_test_case_execution" time="0.0" classname="ScrumBoard.iOS.FunctionalTests.QTiumDemo">
    <skipped/>
  </testcase> <!-- @AfterMethod after_test_case_execution -->
  <testcase name="@AfterMethod after_test_case_execution" time="0.0" classname="ScrumBoard.iOS.FunctionalTests.QTiumDemo">
    <skipped/>
  </testcase> <!-- @AfterMethod after_test_case_execution -->
  <testcase name="@AfterMethod after_test_case_execution" time="0.0" classname="ScrumBoard.iOS.FunctionalTests.QTiumDemo">
    <skipped/>
  </testcase> <!-- @AfterMethod after_test_case_execution -->
  <testcase name="@AfterMethod after_test_case_execution" time="0.0" classname="ScrumBoard.iOS.FunctionalTests.QTiumDemo">
    <skipped/>
  </testcase> <!-- @AfterMethod after_test_case_execution -->
  <testcase name="@AfterMethod after_test_case_execution" time="0.0" classname="ScrumBoard.iOS.FunctionalTests.QTiumDemo">
    <skipped/>
  </testcase> <!-- @AfterMethod after_test_case_execution -->
  <testcase name="@AfterMethod after_test_case_execution" time="0.0" classname="ScrumBoard.iOS.FunctionalTests.QTiumDemo">
    <skipped/>
  </testcase> <!-- @AfterMethod after_test_case_execution -->
  <testcase name="@AfterMethod after_test_case_execution" time="0.0" classname="ScrumBoard.iOS.FunctionalTests.QTiumDemo">
    <skipped/>
  </testcase> <!-- @AfterMethod after_test_case_execution -->
  <testcase name="@AfterClass tear_down" time="0.0" classname="ScrumBoard.iOS.FunctionalTests.QTiumDemo">
    <skipped/>
  </testcase> <!-- @AfterClass tear_down -->
  <testcase name="TC001_Sign_In_Layout" time="0.089" classname="ScrumBoard.Android.FunctionalTests.QTiumDemo">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at com.logigear.selenium.QTiumAutomation.getDriver(QTiumAutomation.java:38)
at com.logigear.selenium.QTiumAutomation.waitForPageToBeReady(QTiumAutomation.java:109)
at com.logigear.selenium.QTiumAutomation.waitForControl(QTiumAutomation.java:142)
at com.logigear.selenium.QTiumAutomation.waitForControl(QTiumAutomation.java:158)
at com.logigear.selenium.QTiumAutomation.isElementExists(QTiumAutomation.java:246)
at ScrumBoard.Android.LoginScreen.CheckAllControls(LoginScreen.java:55)
at ScrumBoard.Android.FunctionalTests.QTiumDemo.TC001_Sign_In_Layout(QTiumDemo.java:38)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- TC001_Sign_In_Layout -->
  <testcase name="TC003_User_cannot_sign_in_with_invalid_credentials" time="0.0" classname="ScrumBoard.Android.FunctionalTests.QTiumDemo">
    <skipped/>
  </testcase> <!-- TC003_User_cannot_sign_in_with_invalid_credentials -->
  <testcase name="TC004_Sign_in_successfully_with_valid_credentials" time="0.0" classname="ScrumBoard.Android.FunctionalTests.QTiumDemo">
    <skipped/>
  </testcase> <!-- TC004_Sign_in_successfully_with_valid_credentials -->
  <testcase name="TC005_Create_Issue_Layout" time="0.0" classname="ScrumBoard.Android.FunctionalTests.QTiumDemo">
    <skipped/>
  </testcase> <!-- TC005_Create_Issue_Layout -->
  <testcase name="TC006_Create_issue_with_invalid_inputs_for_required_fields" time="0.0" classname="ScrumBoard.Android.FunctionalTests.QTiumDemo">
    <skipped/>
  </testcase> <!-- TC006_Create_issue_with_invalid_inputs_for_required_fields -->
  <testcase name="TC007_Create_issue_with_valid_inputs_for_required_fields_successfully" time="0.0" classname="ScrumBoard.Android.FunctionalTests.QTiumDemo">
    <skipped/>
  </testcase> <!-- TC007_Create_issue_with_valid_inputs_for_required_fields_successfully -->
  <testcase name="TC008_User_can_edit_existing_issue_successfully" time="0.0" classname="ScrumBoard.Android.FunctionalTests.QTiumDemo">
    <skipped/>
  </testcase> <!-- TC008_User_can_edit_existing_issue_successfully -->
  <testcase name="TC009_User_can_delete_existing_issue_successfully" time="0.0" classname="ScrumBoard.Android.FunctionalTests.QTiumDemo">
    <skipped/>
  </testcase> <!-- TC009_User_can_delete_existing_issue_successfully -->
  <testcase name="TC001_Sign_In_Layout" time="0.007" classname="ScrumBoard.FunctionalTests.QTiumDemo">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at com.logigear.selenium.QTiumAutomation.getDriver(QTiumAutomation.java:38)
at com.logigear.selenium.QTiumAutomation.waitForPageToBeReady(QTiumAutomation.java:109)
at com.logigear.selenium.QTiumAutomation.waitForControl(QTiumAutomation.java:142)
at com.logigear.selenium.QTiumAutomation.waitForControl(QTiumAutomation.java:158)
at com.logigear.selenium.QTiumAutomation.findElement(QTiumAutomation.java:337)
at ScrumBoard.ScrumBoardPage.isUserProfileDisplay(ScrumBoardPage.java:348)
at ScrumBoard.ScrumBoardPage.expandUserProfile(ScrumBoardPage.java:353)
at ScrumBoard.ScrumBoardPage.logOff(ScrumBoardPage.java:341)
at ScrumBoard.ScrumBoardPage.logOffIfLogin(ScrumBoardPage.java:41)
at ScrumBoard.FunctionalTests.QTiumDemo.TC001_Sign_In_Layout(QTiumDemo.java:36)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- TC001_Sign_In_Layout -->
  <testcase name="TC002_Remember_Me_checkbox" time="0.0" classname="ScrumBoard.FunctionalTests.QTiumDemo">
    <skipped/>
  </testcase> <!-- TC002_Remember_Me_checkbox -->
  <testcase name="TC003_User_cannot_sign_in_with_invalid_credentials" time="0.0" classname="ScrumBoard.FunctionalTests.QTiumDemo">
    <skipped/>
  </testcase> <!-- TC003_User_cannot_sign_in_with_invalid_credentials -->
  <testcase name="TC004_Sign_in_successfully_with_valid_credentials" time="0.0" classname="ScrumBoard.FunctionalTests.QTiumDemo">
    <skipped/>
  </testcase> <!-- TC004_Sign_in_successfully_with_valid_credentials -->
  <testcase name="TC005_Create_Issue_Layout" time="0.0" classname="ScrumBoard.FunctionalTests.QTiumDemo">
    <skipped/>
  </testcase> <!-- TC005_Create_Issue_Layout -->
  <testcase name="TC006_Create_issue_with_invalid_inputs_for_required_fields" time="0.0" classname="ScrumBoard.FunctionalTests.QTiumDemo">
    <skipped/>
  </testcase> <!-- TC006_Create_issue_with_invalid_inputs_for_required_fields -->
  <testcase name="TC007_Create_issue_with_valid_inputs_for_required_fields_successfully" time="0.0" classname="ScrumBoard.FunctionalTests.QTiumDemo">
    <skipped/>
  </testcase> <!-- TC007_Create_issue_with_valid_inputs_for_required_fields_successfully -->
  <testcase name="TC008_User_can_edit_existing_issue_successfully" time="0.0" classname="ScrumBoard.FunctionalTests.QTiumDemo">
    <skipped/>
  </testcase> <!-- TC008_User_can_edit_existing_issue_successfully -->
  <testcase name="TC009_User_can_delete_existing_issue_successfully" time="0.0" classname="ScrumBoard.FunctionalTests.QTiumDemo">
    <skipped/>
  </testcase> <!-- TC009_User_can_delete_existing_issue_successfully -->
  <testcase name="TC001_Order_Item_By_Searching" time="0.021" classname="FptShop.FunctionalTests.QTiumDemo">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at com.logigear.selenium.QTiumAutomation.getDriver(QTiumAutomation.java:38)
at com.logigear.selenium.QTiumAutomation.waitForPageToBeReady(QTiumAutomation.java:109)
at com.logigear.selenium.QTiumAutomation.waitForControl(QTiumAutomation.java:142)
at com.logigear.selenium.QTiumAutomation.waitForControl(QTiumAutomation.java:158)
at com.logigear.selenium.QTiumAutomation.enter(QTiumAutomation.java:221)
at FptShop.AbstractPage.searchItem(AbstractPage.java:17)
at FptShop.FunctionalTests.QTiumDemo.TC001_Order_Item_By_Searching(QTiumDemo.java:66)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- TC001_Order_Item_By_Searching -->
  <testcase name="TC002_Order_Item_By_Category" time="0.0" classname="FptShop.FunctionalTests.QTiumDemo">
    <skipped/>
  </testcase> <!-- TC002_Order_Item_By_Category -->
  <testcase name="TC003_Pre_Order_Item_By_Category_Banner" time="0.0" classname="FptShop.FunctionalTests.QTiumDemo">
    <skipped/>
  </testcase> <!-- TC003_Pre_Order_Item_By_Category_Banner -->
  <testcase name="TC004_Installment_Buying" time="0.0" classname="FptShop.FunctionalTests.QTiumDemo">
    <skipped/>
  </testcase> <!-- TC004_Installment_Buying -->
  <testcase name="TC001_Plus_Function" time="0.002" classname="NativeMac.FunctionalTests.NativeAppDemo">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at com.logigear.selenium.QTiumAutomation.getDriver(QTiumAutomation.java:38)
at com.logigear.selenium.QTiumAutomation.waitForPageToBeReady(QTiumAutomation.java:109)
at com.logigear.selenium.QTiumAutomation.waitForControl(QTiumAutomation.java:142)
at com.logigear.selenium.QTiumAutomation.waitForControl(QTiumAutomation.java:158)
at com.logigear.selenium.QTiumAutomation.click(QTiumAutomation.java:270)
at Calculator.Function.plusTwoNumber(Function.java:19)
at NativeMac.FunctionalTests.NativeAppDemo.TC001_Plus_Function(NativeAppDemo.java:34)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- TC001_Plus_Function -->
  <testcase name="TC002_Minus_Function" time="0.001" classname="NativeMac.FunctionalTests.NativeAppDemo">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at com.logigear.selenium.QTiumAutomation.getDriver(QTiumAutomation.java:38)
at com.logigear.selenium.QTiumAutomation.waitForPageToBeReady(QTiumAutomation.java:109)
at com.logigear.selenium.QTiumAutomation.waitForControl(QTiumAutomation.java:142)
at com.logigear.selenium.QTiumAutomation.waitForControl(QTiumAutomation.java:158)
at com.logigear.selenium.QTiumAutomation.click(QTiumAutomation.java:270)
at Calculator.Function.minusTwoNumber(Function.java:32)
at NativeMac.FunctionalTests.NativeAppDemo.TC002_Minus_Function(NativeAppDemo.java:40)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- TC002_Minus_Function -->
  <testcase name="TC003_Multi_Function" time="0.001" classname="NativeMac.FunctionalTests.NativeAppDemo">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at com.logigear.selenium.QTiumAutomation.getDriver(QTiumAutomation.java:38)
at com.logigear.selenium.QTiumAutomation.waitForPageToBeReady(QTiumAutomation.java:109)
at com.logigear.selenium.QTiumAutomation.waitForControl(QTiumAutomation.java:142)
at com.logigear.selenium.QTiumAutomation.waitForControl(QTiumAutomation.java:158)
at com.logigear.selenium.QTiumAutomation.click(QTiumAutomation.java:270)
at Calculator.Function.multiTwoNumber(Function.java:45)
at NativeMac.FunctionalTests.NativeAppDemo.TC003_Multi_Function(NativeAppDemo.java:46)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- TC003_Multi_Function -->
  <testcase name="TC004_Division_Function" time="0.001" classname="NativeMac.FunctionalTests.NativeAppDemo">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at com.logigear.selenium.QTiumAutomation.getDriver(QTiumAutomation.java:38)
at com.logigear.selenium.QTiumAutomation.waitForPageToBeReady(QTiumAutomation.java:109)
at com.logigear.selenium.QTiumAutomation.waitForControl(QTiumAutomation.java:142)
at com.logigear.selenium.QTiumAutomation.waitForControl(QTiumAutomation.java:158)
at com.logigear.selenium.QTiumAutomation.click(QTiumAutomation.java:270)
at Calculator.Function.divisionTwoNumber(Function.java:58)
at NativeMac.FunctionalTests.NativeAppDemo.TC004_Division_Function(NativeAppDemo.java:52)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- TC004_Division_Function -->
  <testcase name="TC001_Sign_In_Layout" time="0.018" classname="ScrumBoard.iOS.FunctionalTests.QTiumDemo">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at com.logigear.selenium.QTiumAutomation.getDriver(QTiumAutomation.java:38)
at com.logigear.selenium.QTiumAutomation.waitForPageToBeReady(QTiumAutomation.java:109)
at com.logigear.selenium.QTiumAutomation.waitForControl(QTiumAutomation.java:142)
at com.logigear.selenium.QTiumAutomation.waitForControl(QTiumAutomation.java:158)
at com.logigear.selenium.QTiumAutomation.isElementExists(QTiumAutomation.java:246)
at ScrumBoard.iOS.ScrumBoardPage.logOffIfLogin(ScrumBoardPage.java:43)
at ScrumBoard.iOS.FunctionalTests.QTiumDemo.TC001_Sign_In_Layout(QTiumDemo.java:47)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- TC001_Sign_In_Layout -->
  <testcase name="TC001_t" time="0.0" classname="ScrumBoard.iOS.FunctionalTests.QTiumDemo">
    <skipped/>
  </testcase> <!-- TC001_t -->
  <testcase name="TC002_Remember_Me_checkbox" time="0.0" classname="ScrumBoard.iOS.FunctionalTests.QTiumDemo">
    <skipped/>
  </testcase> <!-- TC002_Remember_Me_checkbox -->
  <testcase name="TC003_User_cannot_sign_in_with_invalid_credentials" time="0.0" classname="ScrumBoard.iOS.FunctionalTests.QTiumDemo">
    <skipped/>
  </testcase> <!-- TC003_User_cannot_sign_in_with_invalid_credentials -->
  <testcase name="TC004_Sign_in_successfully_with_valid_credentials" time="0.0" classname="ScrumBoard.iOS.FunctionalTests.QTiumDemo">
    <skipped/>
  </testcase> <!-- TC004_Sign_in_successfully_with_valid_credentials -->
  <testcase name="TC005_Create_Issue_Layout" time="0.0" classname="ScrumBoard.iOS.FunctionalTests.QTiumDemo">
    <skipped/>
  </testcase> <!-- TC005_Create_Issue_Layout -->
  <testcase name="TC006_Create_issue_with_invalid_inputs_for_required_fields" time="0.0" classname="ScrumBoard.iOS.FunctionalTests.QTiumDemo">
    <skipped/>
  </testcase> <!-- TC006_Create_issue_with_invalid_inputs_for_required_fields -->
  <testcase name="TC007_Create_issue_with_valid_inputs_for_required_fields_successfully" time="0.0" classname="ScrumBoard.iOS.FunctionalTests.QTiumDemo">
    <skipped/>
  </testcase> <!-- TC007_Create_issue_with_valid_inputs_for_required_fields_successfully -->
  <testcase name="TC008_User_can_edit_existing_issue_successfully" time="0.0" classname="ScrumBoard.iOS.FunctionalTests.QTiumDemo">
    <skipped/>
  </testcase> <!-- TC008_User_can_edit_existing_issue_successfully -->
  <testcase name="TC009_User_can_delete_existing_issue_successfully" time="0.0" classname="ScrumBoard.iOS.FunctionalTests.QTiumDemo">
    <skipped/>
  </testcase> <!-- TC009_User_can_delete_existing_issue_successfully -->
</testsuite> <!-- Default test -->
