<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="8" hostname="nguyens-Mac.local" name="ScrumBoard.FunctionalTests.QTiumDemo" tests="10" failures="0" timestamp="12 Apr 2018 11:13:28 GMT" time="0.007" errors="2">
  <testcase name="TC006_Create_issue_with_invalid_inputs_for_required_fields" time="0.000" classname="ScrumBoard.FunctionalTests.QTiumDemo">
    <skipped/>
  </testcase> <!-- TC006_Create_issue_with_invalid_inputs_for_required_fields -->
  <testcase name="TC007_Create_issue_with_valid_inputs_for_required_fields_successfully" time="0.000" classname="ScrumBoard.FunctionalTests.QTiumDemo">
    <skipped/>
  </testcase> <!-- TC007_Create_issue_with_valid_inputs_for_required_fields_successfully -->
  <testcase name="TC005_Create_Issue_Layout" time="0.000" classname="ScrumBoard.FunctionalTests.QTiumDemo">
    <skipped/>
  </testcase> <!-- TC005_Create_Issue_Layout -->
  <testcase name="TC008_User_can_edit_existing_issue_successfully" time="0.000" classname="ScrumBoard.FunctionalTests.QTiumDemo">
    <skipped/>
  </testcase> <!-- TC008_User_can_edit_existing_issue_successfully -->
  <testcase name="TC004_Sign_in_successfully_with_valid_credentials" time="0.000" classname="ScrumBoard.FunctionalTests.QTiumDemo">
    <skipped/>
  </testcase> <!-- TC004_Sign_in_successfully_with_valid_credentials -->
  <testcase name="TC009_User_can_delete_existing_issue_successfully" time="0.000" classname="ScrumBoard.FunctionalTests.QTiumDemo">
    <skipped/>
  </testcase> <!-- TC009_User_can_delete_existing_issue_successfully -->
  <testcase name="TC003_User_cannot_sign_in_with_invalid_credentials" time="0.000" classname="ScrumBoard.FunctionalTests.QTiumDemo">
    <skipped/>
  </testcase> <!-- TC003_User_cannot_sign_in_with_invalid_credentials -->
  <testcase name="TC002_Remember_Me_checkbox" time="0.000" classname="ScrumBoard.FunctionalTests.QTiumDemo">
    <skipped/>
  </testcase> <!-- TC002_Remember_Me_checkbox -->
  <testcase name="after_test_case_execution" time="0.000" classname="ScrumBoard.FunctionalTests.QTiumDemo">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at com.logigear.qtium.driver.QTiumDriverManager.getDriver(QTiumDriverManager.java:17)
at com.logigear.qtium.driver.QTiumDriverManager.closeWebDriver(QTiumDriverManager.java:79)
at com.logigear.selenium.QTiumAutomation.close(QTiumAutomation.java:484)
at ScrumBoard.FunctionalTests.QTiumDemo.after_test_case_execution(QTiumDemo.java:29)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:455)
at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- after_test_case_execution -->
  <testcase name="TC001_Sign_In_Layout" time="0.007" classname="ScrumBoard.FunctionalTests.QTiumDemo">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at com.logigear.selenium.QTiumAutomation.getDriver(QTiumAutomation.java:38)
at com.logigear.selenium.QTiumAutomation.waitForPageToBeReady(QTiumAutomation.java:109)
at com.logigear.selenium.QTiumAutomation.waitForControl(QTiumAutomation.java:142)
at com.logigear.selenium.QTiumAutomation.waitForControl(QTiumAutomation.java:158)
at com.logigear.selenium.QTiumAutomation.findElement(QTiumAutomation.java:337)
at ScrumBoard.ScrumBoardPage.isUserProfileDisplay(ScrumBoardPage.java:348)
at ScrumBoard.ScrumBoardPage.expandUserProfile(ScrumBoardPage.java:353)
at ScrumBoard.ScrumBoardPage.logOff(ScrumBoardPage.java:341)
at ScrumBoard.ScrumBoardPage.logOffIfLogin(ScrumBoardPage.java:41)
at ScrumBoard.FunctionalTests.QTiumDemo.TC001_Sign_In_Layout(QTiumDemo.java:36)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- TC001_Sign_In_Layout -->
</testsuite> <!-- ScrumBoard.FunctionalTests.QTiumDemo -->
